config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/' => 'home#top', as: 'top'
  get '/about' => 'home#about'

  resources :users, only: [:show, :index, :edit, :update]
  resources :books, only: [:show, :index, :edit, :update, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true

  validates :body, presence: true,length: { maximum: 200 }

 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy

  attachment :image

  validates :name, presence: true,length: { minimum: 2 }

  validates :name, presence: true,length: { maximum: 20 }

   validates :introduction, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for resource
     top_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:log_in, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
  end

  def index
    @books = Book.page(params[:page]).reverse_order
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to book_path(@book)
    end
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@new_book)
    else
     @books = Book.page(params[:page]).reverse_order
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to book_path(@book)
    end
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to book_path(@book)
    end
    @book.destroy
    redirect_to books_path(@book)
  end

  private

  def book_params
      params.require(:book).permit(:title, :body, :user_image)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @new_book = Book.new
  end

  def index
    @users = User.page(params[:page]).reverse_order
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to user_path(@user)
    else
      # @user = User.find(params[:id])
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>New book</h2>
<%= form_for(new_book) do |f| %>

     <div class="field row">
      <%= f.label :Title, class: "book_title" %>
      <%= f.text_field :title, class: "col-xs-12 book_title" %>
     </div>
     <div class="field row">
       <%= f.label :Opinion, class: "book_body" %>
       <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="actions row">
       <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12"%>
      </div>
     <% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>

        <div id = "error_explanation">
        <% if @book.errors.any? %>
          <%= @book.errors.count %>件のエラーが発生しました
            <% @book.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
        <% end %>
        </div>

         <%= form_for(@book) do |f| %>

            <div class="field row">
                <%= f.label :Title, class: "book_title col-xs-12" %>
                <%= f.text_field :title, class: "book_title col-xs-12" %>
            </div>
            <div class="field row">
                <%= f.label :Opinion, class: "book_body col-xs-12" %>
                <%= f.text_area :body, class: "book_body col-xs-12" %>
            </div>
             <div class="actions row">
                <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
             </div>
        <% end %>
        <%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
        |
        <%= link_to "Back", books_path, class: "books" %>
    </div>
    <div class="col-md-3"></div>
</div>

app/views/books/index.html.erb
<div id="error_explanation" >
<% if @new_book.errors.any? %>
  <%= @new_book.errors.count %>件のエラーが発生しました
    <% @new_book.errors.full_messages.each do |message| %>
      <%= message %>
  <% end %>
<% end %>
</div>
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <table class="table">
        <tr><%= attachment_image_tag current_user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
    </table>
    <div class="row">
      <%= link_to  "",  edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}"  %>
    </div>

     <%= render 'books/list', new_book: @new_book %>




  </div>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |books| %>
        <tr>
           <td>
            <%= link_to user_path(books.user.id), class: "user_#{books.id}" do %>
            <%= attachment_image_tag books.user, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
            <% end %>
          </td>
           <td><%= link_to book_path(books.id), class:
           "book_#{books.id}" do %><%= books.title %><% end %>
         </td>
           <td><%= books.body %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= paginate @books, class: "pagenate" %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>

    <table class="table">
        <tr><%= attachment_image_tag current_user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= @book.user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @book.user.introduction %></th>
        </tr>
    </table>
    <div class="row">
      <%= link_to  "",  edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@book.id}"  %>
    </div>


    <%= render 'books/list', new_book: @new_book %>

  </div>
  <div class="col-xs-9">
    <h2>Books detail</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book.user), class: "user_#{@book.id}" do %>
            <%= attachment_image_tag @book.user, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %><br>
           <%= @book.user.name %>
           <% end %>
         </td>
           <% if @book.user == current_user %>
           <td> <%= link_to book_path, class: "book_#{@book.id}" do %>
           <%= @book.title %>
           <% end %></td>
           <td><%= @book.body %></td>
           <td> <%= link_to  "Edit",  edit_book_path, class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
           <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
           <% else %>
           <td> <%= link_to book_path, class: "book_#{@book.id}" do %>
           <%= @book.title %>
           <% end %></td>
           <td><%= @book.body %></td>
           <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/home/about.html.erb
<h1>
	Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!
</h1>

app/views/home/top.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span>　!!</h1>
    <p>In <span class="glyphicon glyphicon-book"><strong>Bookers</strong></span>,</p>
    <p>
      you can share and exchange your opinions ,
      inpressions , and emotions
    </p>
    <p>
      about varioius books!
    </p>
    <div class="btn-wrapper">
      <div class="row">
        <p>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info
              col-xs-10 col-xs-offset-1 sign_in" %>
        </p>
      </div>
      <div class="row">
        <p>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success
               col-xs-10 col-xs-offset-1 sign_up" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav class="nav navbar-nav navbar-left">
            <span>Bookers</span>
          </nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>

              <li><%=link_to " Home", user_path(current_user), class: "glyphicon glyphicon-home home" %></li>
              <li><%=link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
              <li><%=link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
              <li><%=link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout " %></li>
              <% else %>
              <li><%=link_to " Home", top_path, class: "glyphicon glyphicon-home home" %></li>
              <li><%=link_to " About", about_path, class: "glyphicon glyphicon-link about" %></li>
              <li><%=link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
              <li><%=link_to " login", new_user_session_path,  class: "glyphicon glyphicon-log-in sign_in"%></li>
               <% end %>
            </ul>

          </nav>
        </div>
    </header>

    <div class="body">
      <div class="container">
       <p id="notice"><%= flash[:notice]%></p>
        <%= yield %>
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
<h2>New book</h2>
<%= form_for(new_book) do |f| %>

     <div class="field row">
      <%= f.label :Title, class: "book_title" %>
      <%= f.text_field :title, class: "col-xs-12 book_title" %>
     </div>
     <div class="field row">
       <%= f.label :Opinion, class: "book_body" %>
       <%= f.text_area :body, class: "col-xs-12 book_body"%>
      </div>
      <div class="actions row">
       <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12"%>
      </div>
     <% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
<div id="error_explanation" >
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
<% end %>
</div>
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :Name, class: "name" %>
    <%= f.text_field :name, class: "name" %>
  </div>
  <div class="field">
     <%= f.label :image, class: "user_image" %>
     <%= f.attachment_field :image , class: "user_image"%>
  </div>
  <div class="field">
    <%= f.label :Introduction, class: "introduction"%>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>
  <div class="actions">
    <%= f.submit 'Update User' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <table class="table">
        <tr><%= attachment_image_tag current_user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "user_imgae" %></tr>
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
    </table>
    <div class="row">
    <%= link_to  "",  edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}"  %>
    </div>

    <%= render 'users/list', new_book: @new_book %>

  </div>
  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |f| %>
        <tr>
           <td><%= attachment_image_tag f, :image, :fill, 60, 60, fallback: "no_image.jpg" %> </td>
           <td><%= f.name %></td>
           <td><%= link_to "Show", user_path(f.id), class: "user_#{f.id}" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= paginate @users, class: "pagenate" %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <table class="table">
        <tr><%= attachment_image_tag @user, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
    </table>
    <div class="row">
      <% if @user == current_user %>
      <%= link_to  "",  edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{current_user.id}"  %>
    <% else %>
      <%= link_to  "",  user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user_#{current_user.id}"  %>
    <% end %>
    </div>

    <%= render 'users/list', new_book: @new_book %>


  </div>
  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
      <% @user.books.each do |f| %>
        <tr>
           <th>
            <%= link_to user_path(f.user), class: "user_#{f.id}" do %>
           <%= attachment_image_tag @user, :image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
           <% end %>
           </th>
           <th>
           <%= link_to book_path(f.id), class: "book_#{f.id}" do %>
           <%= f.title %>
           <% end %>
           </th>
           <th><%= f.body %></th>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>